export type HighOneCoreQuestion = {
  id: string;
  questionType: "single_choice" | "multiple_choice" | "fill_blank" | "solution";
  stem: string;
  options?: string[];
  answer: string;
  solution: string;
  primaryKnowledgePoint: string;
  relatedKnowledgePoints?: string[];
  methodTags: string[];
  difficultyScore: number;
  estimatedMinutes: number;
  score: number;
  rubric?: Array<{
    label: string;
    description: string;
    points: number;
    evidenceRequired: string;
    followThroughAllowed?: boolean;
    commonErrors?: string[];
  }>;
};

export const highOneCoreQuestions: HighOneCoreQuestion[] = [
  {
    id: "set-parameter-subset-01",
    questionType: "fill_blank",
    primaryKnowledgePoint: "集合与常用逻辑用语",
    stem: "已知集合 $A=\\{x\\mid x^2-3x+2=0\\}$，$B=\\{1,a\\}$，若 $A\\subseteq B$，则 $a=$______。",
    answer: "2",
    solution: "$x^2-3x+2=(x-1)(x-2)$，所以 $A=\\{1,2\\}$。由 $A\\subseteq B=\\{1,a\\}$ 可知 $a=2$。",
    methodTags: ["方程解集", "子集关系", "参数确定"],
    difficultyScore: 2.2,
    estimatedMinutes: 4,
    score: 5,
  },
  {
    id: "set-logic-solution-01",
    questionType: "single_choice",
    primaryKnowledgePoint: "集合与常用逻辑用语",
    stem: "命题“若 $x>2$，则 $x^2>4$”的逆否命题是（　）",
    options: ["A. 若 $x^2>4$，则 $x>2$", "B. 若 $x\\le2$，则 $x^2\\le4$", "C. 若 $x^2\\le4$，则 $x\\le2$", "D. 若 $x^2<4$，则 $x<2$"],
    answer: "C",
    solution: "命题“若 $p$，则 $q$”的逆否命题为“若非 $q$，则非 $p$”。这里非 $q$ 为 $x^2\\le4$，非 $p$ 为 $x\\le2$。",
    methodTags: ["逆否命题", "条件否定"],
    difficultyScore: 2.0,
    estimatedMinutes: 3,
    score: 5,
  },
  {
    id: "function-domain-composite-01",
    questionType: "fill_blank",
    primaryKnowledgePoint: "函数概念与性质",
    stem: "函数 $f(x)=\\dfrac{\\sqrt{x-1}}{x-3}$ 的定义域为______。",
    answer: "[1,3)\\cup(3,+\\infty)",
    solution: "根式要求 $x-1\\ge0$，分母要求 $x-3\\ne0$。合并得 $x\\ge1$ 且 $x\\ne3$，即 $[1,3)\\cup(3,+\\infty)$。",
    methodTags: ["定义域", "根式条件", "分母不为零"],
    difficultyScore: 2.3,
    estimatedMinutes: 5,
    score: 5,
  },
  {
    id: "function-parity-parameter-01",
    questionType: "fill_blank",
    primaryKnowledgePoint: "函数概念与性质",
    stem: "若函数 $f(x)=x^2+(a-1)x+2$ 为偶函数，则 $a=$______。",
    answer: "1",
    solution: "二次项和常数项本身为偶函数；一次项系数必须为 $0$，所以 $a-1=0$，$a=1$。",
    methodTags: ["偶函数", "参数确定", "奇次项系数"],
    difficultyScore: 2.1,
    estimatedMinutes: 4,
    score: 5,
  },
  {
    id: "function-monotonic-solution-01",
    questionType: "solution",
    primaryKnowledgePoint: "函数概念与性质",
    stem: "已知函数 $f(x)=x^2-2x+3$。求 $f(x)$ 在区间 $[0,3]$ 上的最小值，并说明理由。",
    answer: "最小值为 $2$。",
    solution: "$f(x)=x^2-2x+3=(x-1)^2+2$。当 $x=1$ 时取得最小值 $2$，且 $1\\in[0,3]$，所以区间 $[0,3]$ 上的最小值为 $2$。",
    methodTags: ["配方法", "二次函数最值", "区间检查"],
    difficultyScore: 2.4,
    estimatedMinutes: 8,
    score: 10,
    rubric: [
      { label: "配方", description: "将函数化为顶点式", points: 4, evidenceRequired: "写出 $(x-1)^2+2$ 或等价形式" },
      { label: "检查顶点", description: "确认顶点横坐标在给定区间内", points: 3, evidenceRequired: "说明 $1\\in[0,3]$" },
      { label: "结论", description: "写出最小值", points: 3, evidenceRequired: "明确最小值为 $2$" },
    ],
  },
  {
    id: "function-image-transform-01",
    questionType: "single_choice",
    primaryKnowledgePoint: "函数概念与性质",
    stem: "函数 $y=(x-2)^2+1$ 的图象可由 $y=x^2$ 的图象（　）得到。",
    options: ["A. 向左平移2个单位，再向上平移1个单位", "B. 向右平移2个单位，再向上平移1个单位", "C. 向右平移2个单位，再向下平移1个单位", "D. 向左平移2个单位，再向下平移1个单位"],
    answer: "B",
    solution: "$x$ 替换为 $x-2$ 表示向右平移2个单位，外部加 $1$ 表示向上平移1个单位。",
    methodTags: ["函数图象平移", "二次函数"],
    difficultyScore: 2.0,
    estimatedMinutes: 3,
    score: 5,
  },
  {
    id: "exp-log-domain-01",
    questionType: "fill_blank",
    primaryKnowledgePoint: "指数函数与对数函数",
    stem: "函数 $f(x)=\\log_2(x-1)$ 的定义域为______。",
    answer: "(1,+\\infty)",
    solution: "对数真数必须大于 $0$，所以 $x-1>0$，即 $x>1$。",
    methodTags: ["对数真数", "定义域"],
    difficultyScore: 1.8,
    estimatedMinutes: 3,
    score: 5,
  },
  {
    id: "exp-inequality-01",
    questionType: "single_choice",
    primaryKnowledgePoint: "指数函数与对数函数",
    stem: "不等式 $2^x>8$ 的解集为（　）",
    options: ["A. $x>2$", "B. $x>3$", "C. $x<3$", "D. $x\\ge3$"],
    answer: "B",
    solution: "$8=2^3$，且 $2^x$ 单调递增，因此 $2^x>2^3$ 等价于 $x>3$。",
    methodTags: ["指数函数单调性", "同底比较"],
    difficultyScore: 2.0,
    estimatedMinutes: 3,
    score: 5,
  },
  {
    id: "log-equation-domain-01",
    questionType: "solution",
    primaryKnowledgePoint: "指数函数与对数函数",
    stem: "解方程 $\\log_2(x-1)+\\log_2(x+1)=3$。",
    answer: "$x=3$。",
    solution: "定义域要求 $x>1$。由对数运算得 $\\log_2[(x-1)(x+1)]=3$，所以 $x^2-1=8$，$x^2=9$。结合 $x>1$，得 $x=3$。",
    relatedKnowledgePoints: ["函数概念与性质"],
    methodTags: ["对数运算", "定义域检查", "方程求解"],
    difficultyScore: 2.7,
    estimatedMinutes: 9,
    score: 12,
    rubric: [
      { label: "定义域", description: "写出 $x>1$", points: 3, evidenceRequired: "出现真数均大于0的条件" },
      { label: "合并对数", description: "将左边合并为一个对数", points: 4, evidenceRequired: "写出 $\\log_2[(x-1)(x+1)]$" },
      { label: "求解并取舍", description: "解出候选根并结合定义域取舍", points: 5, evidenceRequired: "排除 $x=-3$，保留 $x=3$", followThroughAllowed: true },
    ],
  },
  {
    id: "trig-identity-transform-01",
    questionType: "fill_blank",
    primaryKnowledgePoint: "三角函数",
    stem: "若 $\\sin\\alpha=\\frac{5}{13}$，且 $\\alpha$ 为第二象限角，则 $\\cos\\alpha=$______。",
    answer: "-\\frac{12}{13}",
    solution: "$\\cos^2\\alpha=1-\\sin^2\\alpha=1-25/169=144/169$。第二象限余弦为负，所以 $\\cos\\alpha=-12/13$。",
    methodTags: ["同角三角函数关系", "象限符号"],
    difficultyScore: 2.1,
    estimatedMinutes: 4,
    score: 5,
  },
  {
    id: "trig-period-01",
    questionType: "single_choice",
    primaryKnowledgePoint: "三角函数",
    stem: "函数 $y=\\sin(2x)$ 的最小正周期为（　）",
    options: ["A. $2\\pi$", "B. $\\pi$", "C. $\\frac{\\pi}{2}$", "D. $4\\pi$"],
    answer: "B",
    solution: "$y=\\sin(\\omega x)$ 的周期为 $\\frac{2\\pi}{|\\omega|}$，这里 $\\omega=2$，所以周期为 $\\pi$。",
    methodTags: ["三角函数周期"],
    difficultyScore: 1.8,
    estimatedMinutes: 3,
    score: 5,
  },
  {
    id: "trig-simplify-01",
    questionType: "solution",
    primaryKnowledgePoint: "三角函数",
    stem: "已知 $\\sin\\alpha+\\cos\\alpha=\\frac{7}{5}$，求 $\\sin\\alpha\\cos\\alpha$。",
    answer: "$\\frac{12}{25}$。",
    solution: "两边平方：$(\\sin\\alpha+\\cos\\alpha)^2=1+2\\sin\\alpha\\cos\\alpha$。所以 $\\frac{49}{25}=1+2\\sin\\alpha\\cos\\alpha$，得 $\\sin\\alpha\\cos\\alpha=\\frac{12}{25}$。",
    methodTags: ["平方转化", "同角关系", "整体代换"],
    difficultyScore: 2.5,
    estimatedMinutes: 8,
    score: 10,
    rubric: [
      { label: "平方关系", description: "建立 $(\\sin\\alpha+\\cos\\alpha)^2=1+2\\sin\\alpha\\cos\\alpha$", points: 5, evidenceRequired: "写出平方展开和 $\\sin^2+\\cos^2=1$" },
      { label: "代入计算", description: "代入 $7/5$ 并求出结果", points: 3, evidenceRequired: "出现 $49/25=1+2\\sin\\alpha\\cos\\alpha$" },
      { label: "结论", description: "写出最终答案", points: 2, evidenceRequired: "答案为 $12/25$" },
    ],
  },
  {
    id: "vector-parameter-parallel-01",
    questionType: "fill_blank",
    primaryKnowledgePoint: "平面向量",
    stem: "已知 $\\vec a=(2,3)$，$\\vec b=(4,m)$，若 $\\vec a\\parallel\\vec b$，则 $m=$______。",
    answer: "6",
    solution: "平行向量坐标成比例，$\\frac{4}{2}=2$，所以 $m=3\\times2=6$。",
    methodTags: ["向量平行", "坐标比例"],
    difficultyScore: 2.0,
    estimatedMinutes: 3,
    score: 5,
  },
  {
    id: "vector-dot-angle-01",
    questionType: "single_choice",
    primaryKnowledgePoint: "平面向量",
    stem: "已知 $|\\vec a|=2$，$|\\vec b|=3$，夹角为 $60^\\circ$，则 $\\vec a\\cdot\\vec b=$（　）",
    options: ["A. $3$", "B. $6$", "C. $\\sqrt3$", "D. $-3$"],
    answer: "A",
    solution: "$\\vec a\\cdot\\vec b=|\\vec a||\\vec b|\\cos60^\\circ=2\\times3\\times\\frac12=3$。",
    methodTags: ["数量积定义", "夹角"],
    difficultyScore: 1.9,
    estimatedMinutes: 3,
    score: 5,
  },
  {
    id: "vector-projection-solution-01",
    questionType: "solution",
    primaryKnowledgePoint: "平面向量",
    stem: "已知 $\\vec a=(1,2)$，$\\vec b=(3,1)$。求 $\\vec a\\cdot\\vec b$，并判断两向量夹角是锐角、直角还是钝角。",
    answer: "$\\vec a\\cdot\\vec b=5$，夹角为锐角。",
    solution: "$\\vec a\\cdot\\vec b=1\\times3+2\\times1=5$。因为数量积大于 $0$，所以夹角为锐角。",
    methodTags: ["数量积坐标运算", "夹角判断"],
    difficultyScore: 2.0,
    estimatedMinutes: 7,
    score: 10,
    rubric: [
      { label: "数量积计算", description: "正确计算坐标形式数量积", points: 5, evidenceRequired: "写出 $1\\times3+2\\times1=5$" },
      { label: "符号判断", description: "用数量积正负判断夹角类型", points: 3, evidenceRequired: "说明数量积大于0" },
      { label: "结论", description: "写出锐角结论", points: 2, evidenceRequired: "明确夹角为锐角" },
    ],
  },
  {
    id: "probability-two-dice-sum-01",
    questionType: "single_choice",
    primaryKnowledgePoint: "概率",
    stem: "同时掷两枚质地均匀的骰子，点数之和为 $7$ 的概率为（　）",
    options: ["A. $\\frac16$", "B. $\\frac{1}{9}$", "C. $\\frac{5}{36}$", "D. $\\frac{7}{36}$"],
    answer: "A",
    solution: "共有 $36$ 个等可能有序结果，和为 $7$ 的结果有 $(1,6),(2,5),(3,4),(4,3),(5,2),(6,1)$ 共 $6$ 个，概率为 $6/36=1/6$。",
    methodTags: ["古典概型", "有序样本空间"],
    difficultyScore: 2.0,
    estimatedMinutes: 4,
    score: 5,
  },
  {
    id: "probability-complement-at-least-01",
    questionType: "fill_blank",
    primaryKnowledgePoint: "概率",
    stem: "连续抛三次质地均匀的硬币，至少出现一次正面的概率为______。",
    answer: "\\frac{7}{8}",
    solution: "正难则反。没有正面即三次全反，概率为 $(1/2)^3=1/8$，所以至少一次正面的概率为 $1-1/8=7/8$。",
    methodTags: ["补集思想", "独立重复试验"],
    difficultyScore: 2.0,
    estimatedMinutes: 4,
    score: 5,
  },
  {
    id: "probability-classification-solution-01",
    questionType: "solution",
    primaryKnowledgePoint: "概率",
    stem: "袋中有编号为 $1,2,3,4$ 的四个球，从中不放回地任取两个。求取出的两个球编号之和为奇数的概率。",
    answer: "$\\frac{2}{3}$。",
    solution: "两个编号之和为奇数，当且仅当一奇一偶。奇数球有 $1,3$ 两个，偶数球有 $2,4$ 两个。有利取法为 $2\\times2=4$ 种。总取法为 $\\binom42=6$ 种，所以概率为 $4/6=2/3$。",
    relatedKnowledgePoints: ["计数原理"],
    methodTags: ["古典概型", "分类计数", "奇偶分析"],
    difficultyScore: 2.4,
    estimatedMinutes: 8,
    score: 10,
    rubric: [
      { label: "事件识别", description: "指出和为奇数等价于一奇一偶", points: 3, evidenceRequired: "出现一奇一偶的判断" },
      { label: "有利数", description: "计算有利取法", points: 3, evidenceRequired: "写出 $2\\times2=4$ 或等价列举" },
      { label: "总数与概率", description: "计算总取法并得概率", points: 4, evidenceRequired: "写出 $\\binom42=6$ 和 $2/3$" },
    ],
  },
  {
    id: "statistics-weighted-mean-01",
    questionType: "fill_blank",
    primaryKnowledgePoint: "统计",
    stem: "某次数学小测中，甲同学两部分得分分别为 $80$ 分和 $90$ 分，权重分别为 $40\\%$ 和 $60\\%$，则加权成绩为______分。",
    answer: "86",
    solution: "加权成绩为 $80\\times0.4+90\\times0.6=32+54=86$。",
    methodTags: ["加权平均数"],
    difficultyScore: 1.8,
    estimatedMinutes: 3,
    score: 5,
  },
  {
    id: "statistics-frequency-table-01",
    questionType: "single_choice",
    primaryKnowledgePoint: "统计",
    stem: "某组数据中，区间 $[10,20)$ 的频数为 $12$，总频数为 $60$，则该组频率为（　）",
    options: ["A. $0.12$", "B. $0.2$", "C. $0.5$", "D. $5$"],
    answer: "B",
    solution: "频率为频数除以总频数，即 $12/60=0.2$。",
    methodTags: ["频率", "统计表"],
    difficultyScore: 1.7,
    estimatedMinutes: 3,
    score: 5,
  },
  {
    id: "complex-division-01",
    questionType: "fill_blank",
    primaryKnowledgePoint: "复数",
    stem: "$\\dfrac{1+i}{1-i}=$______。",
    answer: "i",
    solution: "分子分母同乘 $1+i$，得 $\\dfrac{(1+i)^2}{1+1}=\\dfrac{2i}{2}=i$。",
    methodTags: ["复数除法", "共轭化简"],
    difficultyScore: 2.2,
    estimatedMinutes: 4,
    score: 5,
  },
  {
    id: "complex-equation-01",
    questionType: "single_choice",
    primaryKnowledgePoint: "复数",
    stem: "若 $(a+2i)+(3-bi)=4+i$，其中 $a,b\\in\\mathbb R$，则（　）",
    options: ["A. $a=1,b=1$", "B. $a=1,b=-1$", "C. $a=4,b=1$", "D. $a=3,b=2$"],
    answer: "A",
    solution: "等式左边为 $(a+3)+(2-b)i$。比较实部和虚部，得 $a+3=4$，$2-b=1$，所以 $a=1,b=1$。",
    methodTags: ["复数相等", "实虚部比较"],
    difficultyScore: 2.0,
    estimatedMinutes: 4,
    score: 5,
  },
  {
    id: "multiple-choice-function-domain-01",
    questionType: "multiple_choice",
    primaryKnowledgePoint: "函数概念与性质",
    stem: "下列函数的定义域为 $\\mathbb R$ 的是（　）",
    options: ["A. $f(x)=x^2+1$", "B. $f(x)=\\sqrt{x}$", "C. $f(x)=2^x$", "D. $f(x)=\\dfrac1x$"],
    answer: "A,C",
    solution: "$x^2+1$ 和 $2^x$ 对任意实数都有意义；$\\sqrt{x}$ 需要 $x\\ge0$，$1/x$ 需要 $x\\ne0$。",
    methodTags: ["定义域", "多选取舍"],
    difficultyScore: 2.2,
    estimatedMinutes: 5,
    score: 6,
  },
  {
    id: "multiple-choice-vector-01",
    questionType: "multiple_choice",
    primaryKnowledgePoint: "平面向量",
    stem: "已知 $\\vec a=(1,2)$，$\\vec b=(2,4)$，下列说法正确的是（　）",
    options: ["A. $\\vec a\\parallel\\vec b$", "B. $\\vec a\\perp\\vec b$", "C. $\\vec b=2\\vec a$", "D. $\\vec a\\cdot\\vec b=10$"],
    answer: "A,C,D",
    solution: "$\\vec b=2\\vec a$，所以二者平行；数量积为 $1\\times2+2\\times4=10$；不垂直。",
    methodTags: ["向量平行", "数量积", "多选取舍"],
    difficultyScore: 2.3,
    estimatedMinutes: 5,
    score: 6,
  },
  {
    id: "multiple-choice-probability-01",
    questionType: "multiple_choice",
    primaryKnowledgePoint: "概率",
    stem: "从 $1,2,3,4$ 中随机取一个数。设事件 $A=$“取到偶数”，事件 $B=$“取到大于 $2$ 的数”，下列说法正确的是（　）",
    options: ["A. $P(A)=\\frac12$", "B. $P(B)=\\frac12$", "C. $A\\cap B=\\{4\\}$", "D. $A$ 与 $B$ 为对立事件"],
    answer: "A,B,C",
    solution: "$A=\\{2,4\\}$，$B=\\{3,4\\}$，所以 $P(A)=P(B)=1/2$，$A\\cap B=\\{4\\}$。二者有交集，不是对立事件。",
    relatedKnowledgePoints: ["集合与常用逻辑用语"],
    methodTags: ["事件集合表示", "交事件", "多选取舍"],
    difficultyScore: 2.4,
    estimatedMinutes: 5,
    score: 6,
  },
  {
    id: "multiple-choice-exp-log-01",
    questionType: "multiple_choice",
    primaryKnowledgePoint: "指数函数与对数函数",
    stem: "下列等式正确的是（　）",
    options: ["A. $\\log_2 8=3$", "B. $2^{-2}=\\frac14$", "C. $\\log_3 1=1$", "D. $a^0=1\\ (a\\ne0)$"],
    answer: "A,B,D",
    solution: "$\\log_2 8=3$，$2^{-2}=1/4$，$a^0=1(a\\ne0)$ 均正确；$\\log_3 1=0$，所以 C 错。",
    methodTags: ["指数对数运算", "多选取舍"],
    difficultyScore: 2.1,
    estimatedMinutes: 4,
    score: 6,
  },
];

export function validateHighOneCoreQuestion(question: HighOneCoreQuestion) {
  const errors: string[] = [];
  if (!question.stem.trim() || !question.answer.trim() || !question.solution.trim()) errors.push("题干、答案或解析为空");
  if (question.difficultyScore < 1.5 || question.difficultyScore > 3) errors.push("高一核心题难度必须在1.5到3之间");
  if (question.estimatedMinutes < 2 || question.estimatedMinutes > 12) errors.push("预计用时不合理");
  if (question.questionType === "single_choice") {
    if (question.options?.length !== 4) errors.push("单选题必须有4个选项");
    if (!/^[A-D]$/.test(question.answer)) errors.push("单选题答案必须为A-D");
  }
  if (question.questionType === "multiple_choice") {
    if (question.options?.length !== 4) errors.push("多选题必须有4个选项");
    const answers = question.answer.split(",").map((item) => item.trim());
    if (!answers.length || answers.some((item) => !/^[A-D]$/.test(item))) errors.push("多选题答案必须为A-D逗号分隔");
  }
  if (question.questionType === "solution" && !question.rubric?.length) errors.push("解答题必须有评分点");
  return errors;
}
